## Subset data

### This file generates only the data we need for our demonstration--i.e. subsets of the existing data

In [2]:
import pandas as pd

In [ ]:
#Start with the QoL statistics--here we will only use hdi, eys and li for 2023:
df_qol = pd.read_csv("data/cleaned_metrics.csv")
df_qol.head()

,iso3,country,region,hdi_1990,hdi_1995,hdi_2000,hdi_2005,hdi_2010,hdi_2015,hdi_2020,...,le_2020,le_2023,eys_1990,eys_1995,eys_2000,eys_2005,eys_2010,eys_2015,eys_2020,eys_2023
0,AFG,Afghanistan,SA,0.285,0.329,0.351,0.417,0.465,0.496,0.501,...,61.454,66.035,2.936460,4.396441,5.856422,7.858030,9.180810,10.482975,10.705385,10.790143
1,ALB,Albania,ECA,0.654,0.638,0.682,0.723,0.769,0.797,0.794,...,77.824,79.602,11.579340,10.059140,10.821224,12.037810,13.695700,15.453180,14.734850,14.510150
2,DZA,Algeria,AS,0.595,0.608,0.651,0.692,0.718,0.737,0.742,...,73.257,76.261,9.797890,9.958030,11.221960,12.720790,14.238080,14.838025,15.302207,15.495160
3,AND,Andorra,NaN,NaN,NaN,0.825,0.842,0.870,0.869,0.851,...,79.418,84.041,9.567167,10.044951,10.546596,10.486320,12.312045,11.801850,11.911930,14.542790
4,AGO,Angola,SSA,NaN,NaN,0.391,0.463,0.528,0.603,0.610,...,63.116,64.617,3.755630,3.727985,4.821837,6.956729,9.091620,11.748700,12.167600,12.167600

In [12]:
sa_and_usa = df_qol[
    (df_qol['region'] == 'LAC') | (df_qol['iso3'] == 'USA')
]

cols_2023 = ['iso3', 'country', 'region', 'hdi_2023', 'le_2023', 'eys_2023']
sa_and_usa = sa_and_usa[cols_2023]

In [14]:
sa_and_usa.to_csv("data_for_vis/qol.csv")

In [ ]:
#now, handle the immigration statistics:
df_im = pd.read_csv("data/cleaned_migration.csv")
df_im.columns

Index(['Index', 'Region, development group, country or area of destination',
       'Location code of destination',
       'Region, development group, country or area of origin',
       'Location code of origin', '1990', '1995', '2000', '2005', '2010',
       '2015', '2020', '2024', 'destination code', 'origin code'],
      dtype='object')

In [21]:
lac_iso3 = sa_and_usa[sa_and_usa['region'] == 'LAC']['iso3'].tolist()
all_codes = lac_iso3 + ['USA']

migration_subset = df_im[
    (df_im['destination code'].isin(all_codes)) &
    (df_im['origin code'].isin(all_codes))
][['origin code', 'destination code', '2024']]

In [22]:
migration_subset

     origin code destination code     2024
6392         BHS              ATG        1
6393         BRB              ATG      327
6394         CUB              ATG       20
6395         DMA              ATG     5148
6396         DOM              ATG     1934
...          ...              ...      ...
8524         COL              USA  1008875
8525         ECU              USA   561895
8526         GUY              USA   314783
8527         PER              USA   512316
8528         VEN              USA   763915

[625 rows x 3 columns]

In [24]:
migration_subset = df_im[
    (df_im['destination code'] == 'USA') &
    (df_im['origin code'].isin(lac_iso3))
][['origin code', 'destination code', '2024']]

In [25]:
migration_subset

     origin code destination code      2024
8511         CUB              USA   1394750
8512         DOM              USA   1483418
8513         HTI              USA    798232
8514         JAM              USA    910748
8515         TTO              USA    241541
8516         SLV              USA   1569946
8517         GTM              USA   1298936
8518         HND              USA    934727
8519         MEX              USA  11279561
8520         NIC              USA    295024
8521         PAN              USA    161903
8522         ARG              USA    212091
8523         BRA              USA    738994
8524         COL              USA   1008875
8525         ECU              USA    561895
8526         GUY              USA    314783
8527         PER              USA    512316
8528         VEN              USA    763915

In [26]:
migration_subset.to_csv("data_for_vis/migration.csv")

In [ ]:
#finally, only select entries with year 2025 for the deporation: